files:
  include: 'your_path_to_check/**/*.scss'
  ignore:
    - 'your_path_to_ignore/**/*.scss'
options:
  formatter: stylish
rules:
  bem-depth:
    - 1
    - max-depth: 1
  border-zero:
    - 2
    - convention: 'none'
  brace-style:
    - 2
    - style: '1tbs'
    - allow-single-line: false
  class-name-format:
    - 2
    - convention: '^[-_a-z]+$'
  clean-import-paths:
    - 2
    - leading-underscore: true
  empty-args:
    - 2
  empty-line-between-blocks:
    - 0
  extends-before-declarations:
    - 2
  final-newline:
    - 2
  force-attribute-nesting:
    - 0
  force-element-nesting:
    - 1
  force-pseudo-nesting:
    - 0
  function-name-format:
    - 2
    - convention: '^[-_a-z]+$'
  hex-length:
    - 2
  hex-notation:
    - 2
  indentation:
    - 2
  leading-zero:
    - 2
    - include: true
  mixins-before-declarations:
    - 2
  no-color-keywords:
    - 2
  no-color-literals:
    - 2
  no-css-comments:
    - 1
  no-duplicate-properties:
    - 2
  no-empty-rulesets:
    - 2
  no-ids:
    - 2
  no-invalid-hex:
    - 2
  no-mergeable-selectors:
    - 0
  no-misspelled-properties:
    - 1
    -
      'extra-properties':
        - 'overflow-scrolling'
  no-qualifying-elements:
    - 2
    - allow-element-with-attribute: true
  no-trailing-zero:
    - 2
  no-transition-all:
    - 0
  one-declaration-per-line:
    - 2
  placeholder-in-extend:
    - 1
  property-sort-order:
    - 0
  quotes:
    - 2
  single-line-per-selector:
    - 2
  shorthand-values:
    - 2
    - allowed-shorthands:
      - 1
      - 2
      - 3
  space-after-bang:
    - 2
  space-after-colon:
    - 2
  space-after-comma:
    - 2
  space-around-operator:
    - 2
  space-before-brace:
    - 2
  space-between-parens:
    - 2
  trailing-semicolon:
    - 2
  variable-name-format:
    - 2
    - convention: 'hyphenatedlowercase'
  zero-unit:
    - 1
